In [38]:
import numpy as np
import random
t1 = np.arange(12)
t1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [2]:
t1.shape

(12,)

In [4]:
t2 = np.array([[1,2,3],[4,5,6]])
t2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# t2的形状
t2.shape

(2, 3)

In [19]:
# 将t1转换为三行四列的数组
t1.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
# 转换为三维数组
t3 = np.arange(24).reshape(2,3,4)
t3.shape

(2, 3, 4)

In [14]:
t3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [21]:
# 转换为一维数组，与t3.reshape(24)一样
t3.reshape(24,)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [16]:
# 转换为二维数组
t3.reshape(24,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [22]:
# 展开转化为一维数组
t3.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [23]:
# 所有元素都+2
t3 + 2

array([[[ 2,  3,  4,  5],
        [ 6,  7,  8,  9],
        [10, 11, 12, 13]],

       [[14, 15, 16, 17],
        [18, 19, 20, 21],
        [22, 23, 24, 25]]])

In [24]:
# nan,inf无限
t3 / 0

C:\Users\xinle\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\xinle\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[[nan, inf, inf, inf],
        [inf, inf, inf, inf],
        [inf, inf, inf, inf]],

       [[inf, inf, inf, inf],
        [inf, inf, inf, inf],
        [inf, inf, inf, inf]]])

In [25]:
# 对应的数据元素相乘
t3 * t3

array([[[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121]],

       [[144, 169, 196, 225],
        [256, 289, 324, 361],
        [400, 441, 484, 529]]])

In [26]:
# 维度相同的进行计算
t4 = np.arange(4)
t4 - t3

array([[[  0,   0,   0,   0],
        [ -4,  -4,  -4,  -4],
        [ -8,  -8,  -8,  -8]],

       [[-12, -12, -12, -12],
        [-16, -16, -16, -16],
        [-20, -20, -20, -20]]])

In [27]:
t4 = t4.reshape(1,4)
t4 - t3

array([[[  0,   0,   0,   0],
        [ -4,  -4,  -4,  -4],
        [ -8,  -8,  -8,  -8]],

       [[-12, -12, -12, -12],
        [-16, -16, -16, -16],
        [-20, -20, -20, -20]]])

In [31]:
# 创建数组,注意t5范围1-5，不包含6
t4 = np.array([1,2,3,4,5,6])
t5 = np.array(range(1,6))
t5

array([1, 2, 3, 4, 5])

In [32]:
t5.dtype

dtype('int32')

In [34]:
print(type(t5))

<class 'numpy.ndarray'>


In [35]:
# 自定义数组类型
t6 = np.array(range(1,4),dtype=float)
t6.dtype

dtype('float64')

In [36]:
t6 = np.array(range(1,4),dtype="float32")
t6.dtype

dtype('float32')

In [37]:
# 调整数据类型
t7 = t6.astype("int8")
t7.dtype

dtype('int8')

In [39]:
t8 = np.array([random.random() for i in range(10)])
t8.dtype

dtype('float64')

In [41]:
# 保留两位小数
t9 = np.round(t8, 2)
t9

array([0.17, 0.7 , 0.84, 0.93, 0.15, 0.7 , 0.95, 0.19, 0.78, 0.87])